// AUTO-GENERATED by scripts/import-schedule.mjs — do not edit manually
import type { DayPlan } from '../types/dayPlan';

const day1Plan: DayPlan = {
  "day": 1,
  "title": "抵達釜山・入住西面",
  "subtitle": "金海機場 → 西面 Urbanstay → 松亭三代豬肉湯飯 → 田浦文創 → 宵夜布帳馬車",
  "tags": [
    "輕軌 + 地鐵",
    "總車資 ₩1,800",
    "全程約 43 分鐘",
    "抵達時間 15:30"
  ],
  "timeline": [
    {
      "time": "15:30",
      "event": "金海機場降落・入境",
      "dotColor": "accent"
    },
    {
      "time": "15:50",
      "event": "機場換錢 + 領取 Visit Busan Pass",
      "dotColor": "gold"
    },
    {
      "time": "16:10",
      "event": "搭輕軌 504 → 沙上站 501（7 分鐘）",
      "dotColor": "teal"
    },
    {
      "time": "16:25",
      "event": "步行換乘地鐵沙上站 227（6–7 分鐘）",
      "dotColor": "teal"
    },
    {
      "time": "16:40",
      "event": "地鐵 2 號線 → 西面站 219（14 分鐘）",
      "dotColor": "teal"
    },
    {
      "time": "17:00",
      "event": "抵達飯店・check-in・梳洗",
      "dotColor": "blue"
    },
    {
      "time": "18:30",
      "event": "晚餐：松亭三代豬肉湯飯",
      "dotColor": "accent"
    },
    {
      "time": "20:00",
      "event": "田浦文創商圈初探",
      "dotColor": "gold"
    },
    {
      "time": "22:00",
      "event": "宵夜：西面布帳馬車",
      "dotColor": "muted"
    }
  ],
  "sections": [
    {
      "num": "01",
      "title": "抵達金海機場・入境手續",
      "timeRange": "15:30–15:50",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "accent",
          "rows": [
            {
              "label": "入境卡",
              "value": "建議出發前 3 天在網上填寫韓國電子入境卡（e-Arrival Card），大幅縮短排隊時間。若未填，可在飛機上跟空服員索取紙本。"
            },
            {
              "label": "快速通關",
              "value": "已申請 Smart Pass（SES）者可走自動通關，無需排人工審查隊。"
            },
            {
              "label": "出關後",
              "value": "取行李後走綠色通道（無申報）直接出來，右轉跟著 **Light Rail 輕軌**指標走。"
            }
          ]
        },
        {
          "kind": "photo-ref",
          "label": "圖片參考",
          "desc": "出機場後如何找到輕軌指標、過馬路右轉的路線實拍照",
          "links": [
            {
              "text": "→ Debbie 出機場步驟圖解",
              "href": "https://debbiechien.com/busan-gimhae-airport-transportation/",
              "style": "default"
            },
            {
              "text": "→ 機場出口照片教學",
              "href": "https://13blog.tw/busan-tourism-240613/",
              "style": "teal"
            },
            {
              "text": "→ 2026最新入境全程圖解",
              "href": "https://panpanlife.com/busan-arrival/",
              "style": "amber"
            }
          ]
        }
      ]
    },
    {
      "num": "02",
      "title": "機場換錢・儲值交通卡",
      "timeRange": "15:50–16:05",
      "blocks": [
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "gold",
              "label": "①",
              "title": "前往輕軌機場站內的 Money Box 換錢所",
              "body": "出入境大廳後 → 跟著 **Light Rail** 指標出門 → 過斑馬線後**立刻右轉** → 沿棚子走約 5 分鐘到輕軌站入口。\n進輕軌站後、刷卡前，右手邊就是 **Money Box 換錢所**（黃色招牌）。人工窗口 06:00–21:00；門口另有 24 小時自助換匯機（無人機台）。\n換錢需出示護照，直接給台幣即可，無需手續費，匯率優於機場內銀行。",
              "alerts": [
                {
                  "variant": "warn",
                  "text": "⚠ 布帳馬車、小吃攤多為現金消費。建議換 **₩50,000–80,000** 足夠今晚晚餐＋宵夜＋小雜支。"
                }
              ],
              "tickets": [],
              "photoRefs": [
                {
                  "label": "Money Box 長這樣",
                  "desc": "黃色招牌換錢所外觀、換匯流程實拍、門口自助換匯機照片",
                  "links": [
                    {
                      "text": "→ 呆呆齡實拍外觀＋流程",
                      "href": "https://rowing2005.pixnet.net/blog/posts/9577267384",
                      "style": "amber"
                    },
                    {
                      "text": "→ Liz 換錢所全攻略照",
                      "href": "https://lizzzstyle.tw/money-box-gimhae/",
                      "style": "default"
                    },
                    {
                      "text": "→ 黃色招牌實拍",
                      "href": "https://rebeccafoodaily.com/gimhae-airport-money-box/",
                      "style": "teal"
                    }
                  ]
                }
              ]
            },
            {
              "dotColor": "gold",
              "label": "②",
              "title": "儲值交通卡",
              "body": "換完錢後，在輕軌站內找 **藍色箭頭「Self Service Charger」** 儲值機（非售票機）。\n介面可切換**繁體中文**，依畫面操作儲值即可。\n若持 Visit Busan Pass 實體卡，此卡本身含交通卡功能，直接儲值即可。",
              "alerts": [],
              "tickets": [
                {
                  "text": "建議儲值 ₩10,000–20,000（足夠今日全程地鐵來回）"
                }
              ],
              "photoRefs": [
                {
                  "label": "儲值機長這樣",
                  "desc": "輕軌站內儲值機外觀、中文介面操作畫面",
                  "links": [
                    {
                      "text": "→ 儲值機操作圖解（含中文介面）",
                      "href": "https://13blog.tw/busan-tourism-240613/",
                      "style": "teal"
                    },
                    {
                      "text": "→ 自助儲值全程照片",
                      "href": "https://panpanlife.com/busan-arrival/",
                      "style": "amber"
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "num": "03",
      "title": "搭輕軌：機場站（504）→ 沙上站（501）",
      "timeRange": "16:10–16:18｜車程 7 分鐘",
      "blocks": [
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "teal",
              "label": "①",
              "title": "刷卡進站・上 2 樓月台",
              "body": "儲值完成後刷卡進閘機，搭手扶梯到 **2 樓月台**。\n輕軌只有一條線（紫線），月台看指示牌，搭往 **「沙上 Sasang」** 方向（往西釜山）。",
              "alerts": [],
              "tickets": [],
              "photoRefs": [
                {
                  "label": "輕軌月台長這樣",
                  "desc": "機場站月台外觀、紫色輕軌車廂內部、刷卡閘機照片",
                  "links": [
                    {
                      "text": "→ 小梨輕軌月台實拍",
                      "href": "https://judyer.com/lightrailno2/",
                      "style": "teal"
                    },
                    {
                      "text": "→ Debbie 輕軌車廂內部照",
                      "href": "https://debbiechien.com/busan-gimhae-airport-transportation/",
                      "style": "default"
                    },
                    {
                      "text": "→ Funliday 輕軌搭乘步驟圖",
                      "href": "https://www.funliday.com/posts/korean-travel-busan-airport-to-downtown-lrt/",
                      "style": "amber"
                    }
                  ]
                }
              ]
            },
            {
              "dotColor": "teal",
              "label": "②",
              "title": "乘車・共 3 站到沙上",
              "body": "路線：**機場站（504）→ 公項站（503）→ 府院站（502）→ 沙上站（501）**\n車廂門邊螢幕會顯示下一站站名。車程約 **7 分鐘**，非常快，不用擔心坐過站。",
              "alerts": [],
              "tickets": [
                {
                  "text": "504 → 501 ｜ 車程 7 分鐘 ｜ T-money ₩1,300"
                }
              ],
              "photoRefs": []
            },
            {
              "dotColor": "teal",
              "label": "③",
              "title": "沙上站（501）下車・務必刷卡出站",
              "body": "到沙上站後，**一定要刷卡出站**。輕軌與地鐵是兩個不同系統，先出站才能享轉乘優惠。",
              "alerts": [
                {
                  "variant": "warn",
                  "text": "⚠ 沒有刷出站就直接走去地鐵會無法享轉乘優惠，且可能被追加費用。刷出站、走到地鐵站、再刷入站，這三步缺一不可。"
                }
              ],
              "tickets": [],
              "photoRefs": []
            }
          ]
        }
      ]
    },
    {
      "num": "04",
      "title": "步行換乘：輕軌沙上 → 地鐵沙上站（227）",
      "timeRange": "16:18–16:25｜步行 6–7 分鐘",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "teal",
          "rows": [
            {
              "label": "注意",
              "value": "輕軌站與地鐵站**不在同一棟建築**，需步行約 6–7 分鐘。沿路有**綠色指標**引導，路上不需過馬路，有遮蓋不怕雨。"
            }
          ]
        },
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "teal",
              "label": "①",
              "title": "出輕軌閘口・跟著綠色指標走",
              "body": "刷卡出輕軌站後，地板和牆上立刻出現**綠色「2號線」指標**，跟著走就對了。\n沿途是室內走廊，一直走到底看到 **「Tracks to Metro」** 或「地铁乘车处」標示，表示快到了。",
              "alerts": [],
              "tickets": [],
              "photoRefs": [
                {
                  "label": "換乘走廊長這樣",
                  "desc": "地板綠色指標、走廊路線、轉乘過程全程實拍",
                  "links": [
                    {
                      "text": "→ 小梨沙上站換乘完整照片",
                      "href": "https://judyer.com/lightrailno2/",
                      "style": "teal"
                    },
                    {
                      "text": "→ Funliday 地板綠色指標照",
                      "href": "https://www.funliday.com/posts/korean-travel-busan-airport-to-downtown-lrt/",
                      "style": "default"
                    },
                    {
                      "text": "→ 小氣少年換乘路線全程圖",
                      "href": "https://nicklee.tw/2460/pus-airport-transportation/",
                      "style": "amber"
                    }
                  ]
                }
              ]
            },
            {
              "dotColor": "teal",
              "label": "②",
              "title": "找有電梯的閘口再進站",
              "body": "走到地鐵 2 號線入口時，**先不要刷第一個看到的閘機**。\n旁邊指標會寫「電梯在前方 50 公尺」，帶行李的人繼續往前找**有電梯的閘口**再刷卡進站。",
              "alerts": [
                {
                  "variant": "warn",
                  "text": "⚠ 部分閘機有旋轉鐵竿，行李箱容易卡住。找到寬閘口或輪椅通道，把行李箱**先放倒打橫推過去**，人再刷卡跟著進，不要硬擠。"
                }
              ],
              "tickets": [],
              "photoRefs": [
                {
                  "label": "閘機行李通過方式",
                  "desc": "地鐵閘機類型、行李箱過閘方式、電梯位置照片",
                  "links": [
                    {
                      "text": "→ 閘機行李過法實拍說明",
                      "href": "https://nicklee.tw/2460/pus-airport-transportation/",
                      "style": "amber"
                    },
                    {
                      "text": "→ 電梯位置＋閘口照片",
                      "href": "https://www.funliday.com/posts/korea-travel-busan-subway-transfer-informaiton/",
                      "style": "default"
                    }
                  ]
                }
              ]
            },
            {
              "dotColor": "teal",
              "label": "③",
              "title": "刷卡進地鐵沙上站（227）",
              "body": "找到有電梯的閘口後，再次刷卡進站。T-money 自動計算轉乘優惠，30 分鐘內僅追加 **₩500**。",
              "alerts": [],
              "tickets": [
                {
                  "text": "轉乘追加 ₩500（自動扣）｜ 輕軌 ₩1,300 + 轉乘 ₩500 = 合計 ₩1,800"
                }
              ],
              "photoRefs": []
            }
          ]
        }
      ]
    },
    {
      "num": "05",
      "title": "搭地鐵：沙上站（227）→ 西面站（219）",
      "timeRange": "16:25–16:40｜車程 14 分鐘",
      "blocks": [
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "teal",
              "label": "①",
              "title": "找月台・往「甘田 장산方向」",
              "body": "進站後看月台指示牌，搭 2 號線（**綠線**），往 **甘田（장산 Jangsan）**方向，即往東。\n西面是大站，廣播有韓英雙語，聽到 **「Seomyeon」** 就準備下車。",
              "alerts": [],
              "tickets": [],
              "photoRefs": [
                {
                  "label": "地鐵月台怎麼確認方向",
                  "desc": "地鐵 2 號線月台、往甘田方向指示牌、車廂門邊站名顯示螢幕",
                  "links": [
                    {
                      "text": "→ 小梨地鐵搭乘方向圖解",
                      "href": "https://judyer.com/lightrailno2/",
                      "style": "teal"
                    },
                    {
                      "text": "→ 車廂門邊螢幕確認站號",
                      "href": "https://nicklee.tw/2460/pus-airport-transportation/",
                      "style": "default"
                    }
                  ]
                }
              ]
            },
            {
              "dotColor": "teal",
              "label": "②",
              "title": "西面站（219）下車・找電梯出站",
              "body": "車程約 14 分鐘，看車廂螢幕確認站號 **219** 即下車。\n西面站出口多，帶行李請優先找**電梯**，避免扛行李走樓梯。\n出站後直接開 **Naver Map** 導航至飯店，步行 3–8 分鐘。",
              "alerts": [
                {
                  "variant": "note",
                  "text": "ℹ 西面站有 1、2、3、7、8 號等多個出口。往 Urbanstay Seomyeon 飯店的出口依訂房確認，出站後直接開 Naver Map 最保險。"
                }
              ],
              "tickets": [
                {
                  "text": "全程 機場站 504 → 西面站 219 ｜ ₩1,800 ｜ 總時間（含換乘步行） 約 43 分鐘"
                }
              ],
              "photoRefs": [
                {
                  "label": "西面站出站・找電梯",
                  "desc": "西面站月台電梯位置、出口指標、行李過閘方式",
                  "links": [
                    {
                      "text": "→ Funliday 西面站電梯位置",
                      "href": "https://www.funliday.com/posts/korea-travel-busan-subway-transfer-informaiton/",
                      "style": "default"
                    },
                    {
                      "text": "→ 西面站出站完整圖解",
                      "href": "https://nicklee.tw/2460/pus-airport-transportation/",
                      "style": "amber"
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "num": "06",
      "title": "抵達飯店・Check-in",
      "timeRange": "17:00–18:30",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "blue",
          "rows": [
            {
              "label": "飯店",
              "value": "**Urbanstay Seomyeon** 어반스테이 서면｜Day 1–2 住宿"
            },
            {
              "label": "Check-in",
              "value": "一般 15:00 後。若抵達時房間未好，可先寄放行李出門。"
            },
            {
              "label": "預訂提醒",
              "value": "Check-in 後確認飯店是否在 ZIM CARRY 合作名單，若是，在 KKday 預訂 Day 3 行李宅配至海雲台飯店。"
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "tip",
          "text": "💡 整理好行李後輕裝出發。晚上只需帶錢包＋手機＋現金，不用帶大包。"
        }
      ]
    },
    {
      "num": "07",
      "title": "晚餐：松亭三代豬肉湯飯",
      "timeRange": "18:30–19:30",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "accent",
          "rows": [
            {
              "label": "店名",
              "value": "송정3대국밥（松亭三代豬肉湯飯）｜1946年創立，近 80 年老店"
            },
            {
              "label": "位置",
              "value": "西面站 1 號出口步行約 3–5 分鐘。Naver Map 搜尋 **「송정3대국밥 서면」**，沿路看到招牌上有「3代」字樣＋電視台採訪報導貼紙即到。"
            },
            {
              "label": "營業",
              "value": "**24 小時**，任何時間都可以來，幾乎全天都有客人。"
            },
            {
              "label": "付款",
              "value": "現金或刷卡均可。"
            }
          ]
        },
        {
          "kind": "menu",
          "header": "點餐建議（食量小版）",
          "items": [
            {
              "name": "豬肉湯飯 돼지국밥",
              "note": "兩人各一碗，主食"
            },
            {
              "name": "白切肉套餐 수육",
              "note": "可替代湯飯，附小碗湯，肉嫩分量足"
            },
            {
              "name": "血腸 순대",
              "note": "可單點追加，兩人分一份嘗鮮即可"
            },
            {
              "name": "小菜自取區",
              "note": "洋蔥、泡菜、蒜頭、辣韭菜，旁邊有鹽巴可自行調湯頭鹹淡"
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "note",
          "text": "ℹ **點餐流程**：入座後服務員會送上中英文菜單（不會韓文也沒問題），選好後報給服務員即可，不用走到櫃台。湯飯本身**沒有調味**，鹹淡靠鹽巴自己加，喜歡重口味多加一點。"
        },
        {
          "kind": "alert",
          "variant": "tip",
          "text": "💡 食量不大 → 兩人各點一碗湯飯就夠，血腸視情況加點，不要多點，留肚子給宵夜黑糖餅。在地人與觀光客比例約 7:3，氣氛熱鬧不用擔心格格不入。"
        },
        {
          "kind": "photo-ref",
          "label": "餐廳外觀・菜單・上桌照片",
          "desc": "招牌「3代」字樣外觀、中文菜單版本、湯飯端上桌照、小菜自取區、白切肉擺盤",
          "links": [
            {
              "text": "→ 呆呆齡｜招牌＋中文菜單實拍",
              "href": "https://rowing2005.pixnet.net/blog/post/577433816",
              "style": "red"
            },
            {
              "text": "→ Mimi｜店內環境＋湯飯照",
              "href": "https://mimigo.tw/pork-rice-soup/",
              "style": "amber"
            },
            {
              "text": "→ Starseed｜白切肉＋小菜自取照",
              "href": "https://starseedgirl.com/%E3%80%8A%E6%9D%BE%E4%BA%AD%E4%B8%89%E4%BB%A3%E8%B1%AC%E8%82%89%E6%B9%AF%E9%A3%AF%E3%80%8B%EC%86%A1%EC%A0%953%EB%8C%80%EA%B5%AD%EB%B0%A5-%E9%87%9C%E5%B1%B1%C2%B7%E8%A5%BF%E9%9D%A2%E7%AB%99%EF%BD%9C%E9%9F%93%E5%9C%8B/",
              "style": "default"
            },
            {
              "text": "→ 巧莉｜血腸菜單解說",
              "href": "https://ciaoz.tw/songjong-porksoup/",
              "style": "teal"
            }
          ]
        }
      ]
    },
    {
      "num": "08",
      "title": "田浦文創商圈初探",
      "timeRange": "20:00–22:00",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "gold",
          "rows": [
            {
              "label": "位置",
              "value": "從飯店步行約 5–10 分鐘，Naver Map 搜尋「전포카페거리」。"
            },
            {
              "label": "今晚",
              "value": "輕鬆初探，**CRR 寵物店 13:00 才開**，留 Day 5 補逛。"
            }
          ]
        },
        {
          "kind": "steps",
          "items": [
            {
              "dotColor": "gold",
              "label": "①",
              "title": "Object 오브젝트（開到 22:00）",
              "body": "韓國設計選物，文具、生活雜貨，今晚感受氣氛即可。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "gold",
              "label": "②",
              "title": "Butter / ARTBOX（開到 22:00）",
              "body": "同類型雜貨，在 Object 附近，順路看看。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            },
            {
              "dotColor": "gold",
              "label": "③",
              "title": "DAISO（開到 22:00）",
              "body": "若需補充旅行小物（保鮮袋、掛勾等），此時最順路。",
              "alerts": [],
              "tickets": [],
              "photoRefs": []
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "note",
          "text": "ℹ 今晚只是開胃前菜，Day 5 還會再來做完整採買，今晚輕鬆逛就好，不需要什麼都買。"
        }
      ]
    },
    {
      "num": "09",
      "title": "宵夜：西面布帳馬車",
      "timeRange": "22:00–23:00",
      "blocks": [
        {
          "kind": "info-card",
          "variant": "accent",
          "rows": [
            {
              "label": "怎麼找",
              "value": "西面站 **7 號出口**出站，往樂天免稅店方向走，就會看到一整排紅色帆布帳篷的布帳馬車。也可搜尋 Naver Map 서면 포장마차。"
            },
            {
              "label": "開攤時間",
              "value": "黃昏後陸續開攤，**20:00–22:00 最熱鬧**，深夜仍有攤位在。"
            },
            {
              "label": "付款",
              "value": "絕大多數攤位**只收現金**，帶 ₩20,000–30,000 現金出門。"
            },
            {
              "label": "座位",
              "value": "辣炒年糕街的小攤通常**無座位，站著吃**。有紅帳篷的布帳馬車才有矮桌椅可入座，看到空位直接坐下即可，老闆會過來點餐。"
            }
          ]
        },
        {
          "kind": "menu",
          "header": "宵夜必點（食量小→兩樣就夠）",
          "items": [
            {
              "name": "辣炒年糕 떡볶이",
              "note": "兩人分一份，年糕＋魚板一起煮"
            },
            {
              "name": "黑糖餅 호떡",
              "note": "現做熱的最好吃，分食一個"
            },
            {
              "name": "魚板湯 어묵탕",
              "note": "站著吃的攤位通常免費附湯，可以續"
            },
            {
              "name": "炸餃子 / 炸蔬菜 튀김",
              "note": "可選，單點一兩樣嘗鮮"
            }
          ]
        },
        {
          "kind": "alert",
          "variant": "note",
          "text": "ℹ **點餐方式**：有紅帳篷的攤位直接找空位坐，老闆會來問。站著吃的小攤則直接看看板指著說要哪個，或用手機翻譯 App 輔助，老闆通常懂幾句簡單英文，比手畫腳也能通。"
        },
        {
          "kind": "alert",
          "variant": "warn",
          "text": "⚠ 部分攤位針對觀光客定價略高，建議選**旁邊有韓國人在吃的攤位**，或看板上有清楚標價的。點辣炒年糕一份＋黑糖餅一個分食即可，別被老闆推薦點太多，宵夜吃到 ₩10,000–15,000 就非常足夠。"
        },
        {
          "kind": "photo-ref",
          "label": "布帳馬車長這樣・怎麼找・怎麼點",
          "desc": "紅色帆布帳篷外觀、西面一整排布帳馬車夜晚街景、辣炒年糕＋黑糖餅實拍、帳篷內矮桌椅座位",
          "links": [
            {
              "text": "→ Starseed｜西面布帳馬車實拍＋點餐過程",
              "href": "https://starseedgirl.com/%E3%80%8A%E5%B8%83%E5%B8%B3%E9%A6%AC%E8%BB%8A%E4%B8%80%E6%A2%9D%E8%A1%97%E3%80%8B%ED%8F%AC%EC%9E%A5%EB%A7%88%EC%B0%A8-%E9%87%9C%E5%B1%B1%C2%B7%E8%A5%BF%E9%9D%A2%E7%AB%99%EF%BD%9C%E9%9F%93%E5%9C%8B/",
              "style": "red"
            },
            {
              "text": "→ 莓姬貝利｜紅帳篷內部座位＋食物照",
              "href": "https://beri.tw/pojangmacha-busan/",
              "style": "amber"
            },
            {
              "text": "→ 小菲｜西面布帳馬車街景＋找到方式",
              "href": "https://feitravel.tw/blog/post/68753684",
              "style": "default"
            },
            {
              "text": "→ Helena｜布帳馬車文化介紹＋點餐說明",
              "href": "https://helena.tw/busan-station-pojangmacha/",
              "style": "teal"
            }
          ]
        }
      ]
    },
    {
      "num": "10",
      "title": "行前 Checklist",
      "timeRange": "",
      "blocks": [
        {
          "kind": "checklist",
          "items": [
            "出發前：填寫韓國電子入境卡（e-Arrival Card），提前 3 天線上填。",
            "交通卡：T-money、WOWpass 或 Visit Busan Pass 實體卡均可，到機場輕軌站儲值使用。",
            "Visit Busan Pass：Gate 2 旁旅遊諮詢處領取（10:00–17:00，午休 12:00–13:00）。班機 15:30 落地時間剛好，不要拖太久。若過了 17:00 則第二天補領。",
            "換錢：機場輕軌站內 Money Box（黃色招牌），人工窗口 06:00–21:00，門口有 24h 自助機。換 ₩5–8 萬韓幣即可。",
            "沙上換乘：輕軌出站後步行 6–7 分鐘到地鐵站，行李多請多留時間，跟著綠色指標走，找電梯再進站。",
            "飯店確認：抵達後確認 Urbanstay Seomyeon 在 ZIM CARRY 合作名單，於 KKday 預訂 Day 3 行李宅配。",
            "宵夜現金：布帳馬車多為現金，帶 ₩20,000–30,000 出門。",
            "Naver Map：出地鐵站後用 Naver Map 導航飯店，比 Google Map 在釜山更精準。"
          ]
        }
      ]
    }
  ]
};

export default day1Plan;
